name: ByGeorge
favicon: null
layout_spectrum: 0.8685665708035231
typography_spectrum: 0.65085
title: 'Angela & Matt George'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7233943974133581
  lightness: 0.5746647785417736
  saturation: 0.9868062431924045
  rhythmicContrast: 0.977585913380608
purpose: []
